// ═══════════════════════════════════════════════════════════════
// CircumSurvey — Auto-generated aggregate data
// Generated: 2026-04-17 09:33 UTC
// DO NOT EDIT MANUALLY — regenerated by scripts/aggregate.py
// ═══════════════════════════════════════════════════════════════

const _data = {
  "meta": {
    "totalRespondents": 501,
    "phase": "Live · Rolling Count",
    "lastUpdated": "2026-04-21",
    "pathwayCounts": {
      "intact": 142,
      "restoring": 109,
      "circumcised": 213,
      "observer": 37
    }
  },
  "pathway": {
    "intact": {
      "label": "The Intact Pathway",
      "short": "Intact",
      "n": 140,
      "color": "#5b93c7",
      "bg": "rgba(91,147,199,0.12)",
      "emoji": "🟢"
    },
    "circumcised": {
      "label": "The Circumcised Pathway",
      "short": "Circumcised",
      "n": 210,
      "color": "#d94f4f",
      "bg": "rgba(217,79,79,0.12)",
      "emoji": "🔵"
    },
    "restoring": {
      "label": "The Restoration Pathway",
      "short": "Restoring",
      "n": 109,
      "color": "#e8c868",
      "bg": "rgba(232,200,104,0.12)",
      "emoji": "🟣"
    },
    "observer": {
      "label": "The Observer, Partner & Ally Pathway",
      "short": "Observer",
      "n": 37,
      "color": "#a0a0a0",
      "bg": "rgba(160,160,160,0.12)",
      "emoji": "🟠"
    },
    "all_circ": {
      "label": "All Circumcised Respondents",
      "short": "All Circ.",
      "n": 319,
      "color": "#cc6855",
      "bg": "rgba(204,104,85,0.12)",
      "emoji": "🔵🟣"
    }
  },
  "questions": [
  {
    "id": "appearance",
    "cat": "Body Image",
    "q": "Thinking about your penis today, how do you generally FEEL about its physical appearance?",
    "opts": [
      "Very Positive",
      "Positive",
      "Neutral",
      "Negative",
      "I don't really think about its appearance much.",
      "Very Negative"
    ],
    "colors": [
      "#5b93c7",
      "#8bb8d9",
      "#e8c868",
      "#e8a44a",
      "#a0a0a0",
      "#d94f4f"
    ],
    "data": {
      "intact": [
        44.6,
        32.4,
        13.7,
        8.6,
        0.7,
        0
      ],
      "circumcised": [
        11.2,
        26.2,
        15.5,
        24.8,
        1.0,
        21.4
      ],
      "restoring": [
        4.7,
        25.2,
        20.6,
        30.8,
        0,
        18.7
      ]
    },
    "pathways": [
      "intact",
      "circumcised",
      "restoring"
    ]
  },
  {
    "id": "pride",
    "cat": "Body Image",
    "q": "Overall, how PROUD or satisfied are you with your penis?",
    "opts": [
      "Very proud and satisfied",
      "Generally proud and satisfied",
      "Neutral or ambivalent",
      "Somewhat dissatisfied",
      "I don't really frame my feelings about it in terms of 'pride' or 'dissatisfaction'.",
      "Very dissatisfied"
    ],
    "colors": [
      "#5b93c7",
      "#8bb8d9",
      "#e8c868",
      "#e8a44a",
      "#a0a0a0",
      "#d94f4f"
    ],
    "data": {
      "intact": [
        38.7,
        37.2,
        11.7,
        9.5,
        2.2,
        0.7
      ],
      "circumcised": [
        8.3,
        24.8,
        11.7,
        22.3,
        2.4,
        30.6
      ],
      "restoring": [
        7.5,
        16.8,
        12.1,
        37.4,
        1.9,
        24.3
      ]
    },
    "sub": "Considering appearance, function, and pleasure",
    "pathways": [
      "intact",
      "circumcised",
      "restoring"
    ]
  },
  {
    "id": "intensity",
    "cat": "Sexual Experience",
    "q": "Please rate the INTENSITY of your orgasms.",
    "type": "avg",
    "data": {
      "intact": 3.73,
      "circumcised": 2.99,
      "restoring": 2.93
    },
    "sub": "On a 1–5 scale, from the Sexual Experience grid (Q27.1): 1 = Low/Poor, 5 = High/Excellent."
  },
  {
    "id": "duration_r",
    "cat": "Sexual Experience",
    "q": "Please rate the DURATION of your orgasms.",
    "type": "avg",
    "data": {
      "intact": 3.8,
      "circumcised": 2.81,
      "restoring": 2.65
    },
    "sub": "On a 1–5 scale, from the Sexual Experience grid (Q27.2): 1 = Low/Poor, 5 = High/Excellent."
  },
  {
    "id": "ease",
    "cat": "Sexual Experience",
    "q": "Please rate your OVERALL EASE of reaching orgasm.",
    "type": "avg",
    "data": {
      "intact": 3.43,
      "circumcised": 2.91,
      "restoring": 2.8
    },
    "sub": "On a 1–5 scale, from the Sexual Experience grid (Q27.3): 1 = Low/Poor, 5 = High/Excellent."
  },
  {
    "id": "light",
    "cat": "Sexual Experience",
    "q": "Please rate your SENSITIVITY to light touch.",
    "type": "avg",
    "data": {
      "intact": 3.67,
      "circumcised": 2.6,
      "restoring": 2.67
    },
    "sub": "On a 1–5 scale, from the Sexual Experience grid (Q27.4): 1 = Low/Poor, 5 = High/Excellent."
  },
  {
    "id": "mobile",
    "cat": "Sexual Experience",
    "q": "Please rate your PLEASURE from mobile skin.",
    "type": "avg",
    "data": {
      "intact": 3.88,
      "circumcised": 2.49,
      "restoring": 3.0
    },
    "sub": "On a 1–5 scale, from the Sexual Experience grid (Q27.5): 1 = Low/Poor, 5 = High/Excellent."
  },
  {
    "id": "variety",
    "cat": "Sexual Experience",
    "q": "Please rate the VARIETY of pleasurable sensations you experience.",
    "type": "avg",
    "data": {
      "intact": 3.78,
      "circumcised": 2.58,
      "restoring": 2.65
    },
    "sub": "On a 1–5 scale, from the Sexual Experience grid (Q27.6): 1 = Low/Poor, 5 = High/Excellent."
  },
  {
    "id": "confidence",
    "cat": "Sexual Experience",
    "q": "...how would you rate your general confidence that your orgasms are as intense or fulfilling as possible?",
    "opts": [
      "Confident",
      "Extremely confident",
      "Moderately confident",
      "Depends",
      "Something is missing"
    ],
    "colors": [
      "#5b93c7",
      "#8bb8d9",
      "#e8c868",
      "#e8a44a",
      "#d94f4f"
    ],
    "data": {
      "intact": [
        43.3,
        24.6,
        16.4,
        11.2,
        4.5
      ],
      "circumcised": [
        16.1,
        6.5,
        23.1,
        6.0,
        48.2
      ],
      "restoring": [
        7.7,
        5.8,
        19.2,
        7.7,
        59.6
      ]
    },
    "pathways": [
      "intact",
      "circumcised",
      "restoring"
    ],
    "sub": "We're asking about your confidence in your baseline — whether the experience you have is as full as it could be, or whether something is missing."
  },
  {
    "id": "lube",
    "cat": "Sexual Experience",
    "q": "Do you generally need to use artificial LUBRICATION during sexual activity?",
    "opts": [
      "Never",
      "Sometimes",
      "Rarely",
      "Often helpful",
      "Always/almost always",
      "N/A"
    ],
    "colors": [
      "#5b93c7",
      "#8bb8d9",
      "#e8c868",
      "#e8a44a",
      "#d94f4f",
      "#a0a0a0"
    ],
    "data": {
      "intact": [
        55.5,
        19.7,
        18.2,
        5.1,
        1.5,
        0
      ],
      "circumcised": [
        5.5,
        20.0,
        14.5,
        18.0,
        39.0,
        3.0
      ],
      "restoring": [
        16.0,
        17.9,
        17.9,
        14.2,
        33.0,
        0.9
      ]
    },
    "pathways": [
      "intact",
      "circumcised",
      "restoring"
    ]
  },
  {
    "id": "duration",
    "cat": "Sexual Experience",
    "q": "DURATION: How long do the primary pleasurable sensations of your typical orgasm last?",
    "opts": [
      "6–15 sec",
      "16–30 sec",
      "0–5 sec",
      "Up to 1 min",
      "Unsure",
      "Varies",
      "1+ min"
    ],
    "colors": [
      "#e8a44a",
      "#e8c868",
      "#d94f4f",
      "#8bb8d9",
      "#a0a0a0",
      "#a0a0a0",
      "#5b93c7"
    ],
    "data": {
      "intact": [
        40.6,
        29.0,
        14.5,
        6.5,
        5.1,
        2.9,
        1.4
      ],
      "circumcised": [
        34.8,
        12.9,
        38.3,
        7.0,
        1.5,
        3.5,
        2.0
      ],
      "restoring": [
        38.1,
        11.4,
        39.0,
        3.8,
        2.9,
        2.9,
        1.9
      ]
    },
    "pathways": [
      "intact",
      "circumcised",
      "restoring"
    ]
  },
  {
    "id": "sons",
    "cat": "Autonomy & Ethics",
    "q": "Based on everything you know and have experienced, if you were to have a child assigned male at birth today, what would your decision regarding circumcision be?",
    "opts": [
      "Keep intact",
      "N/A",
      "Undecided",
      "Partner's choice",
      "Circumcise"
    ],
    "colors": [
      "#5b93c7",
      "#a0a0a0",
      "#e8c868",
      "#e8a44a",
      "#d94f4f"
    ],
    "data": {
      "intact": [
        88.8,
        7.5,
        2.2,
        1.5,
        0
      ],
      "circumcised": [
        78.1,
        6.0,
        4.0,
        3.5,
        8.5
      ],
      "restoring": [
        98.1,
        1.9,
        0,
        0,
        0
      ],
      "observer": [
        90.9,
        3.0,
        0,
        3.0,
        3.0
      ]
    }
  },
  {
    "id": "autonomy",
    "cat": "Autonomy & Ethics",
    "q": "When considering a NON-THERAPEUTIC, irreversible surgical procedure on a healthy infant, which principle do you believe should be given more weight?",
    "opts": [
      "The recommendation of Medical Authorities and Parental Discretion",
      "The Child's Right to Bodily Autonomy"
    ],
    "colors": [
      "#d94f4f",
      "#5b93c7"
    ],
    "data": {
      "intact": [
        96.4,
        3.6
      ],
      "circumcised": [
        81.3,
        18.7
      ],
      "restoring": [
        100.0,
        0
      ],
      "observer": [
        97.0,
        3.0
      ]
    }
  },
  {
    "id": "handled",
    "cat": "Decision & Consent",
    "q": "Based on what you know, how was the topic of circumcision likely handled around the time of your birth?",
    "opts": [
      "Routine / automatic",
      "No idea",
      "Strong medical rec.",
      "Not brought up",
      "Neutral pros & cons"
    ],
    "colors": [
      "#d94f4f",
      "#a0a0a0",
      "#e8a44a",
      "#e8c868",
      "#5b93c7"
    ],
    "data": {
      "circumcised": [
        47.6,
        23.2,
        18.9,
        7.6,
        2.7
      ]
    },
    "note": "Asked of Circumcised Pathway respondents only.",
    "pathways": [
      "circumcised"
    ]
  },
  {
    "id": "norm",
    "cat": "Decision & Consent",
    "q": "In your family or the community you grew up in, what was the general EXPECTATION for newborn boys regarding circumcision?",
    "opts": [
      "Uncommon",
      "Unquestioned norm",
      "Very common",
      "50/50",
      "Not sure"
    ],
    "colors": [
      "#5b93c7",
      "#d94f4f",
      "#e8a44a",
      "#e8c868",
      "#a0a0a0"
    ],
    "data": {
      "intact": [
        33.8,
        23.5,
        22.8,
        12.5,
        7.4
      ],
      "circumcised": [
        22.9,
        47.3,
        14.4,
        6.0,
        9.5
      ],
      "restoring": [
        16.5,
        54.1,
        16.5,
        2.8,
        10.1
      ],
      "observer": [
        11.8,
        44.1,
        32.4,
        5.9,
        5.9
      ]
    },
    "sub": "This question tries to get at the power of social conformity and default settings. Was circumcision the unquestioned norm, or was it truly seen as an optional choice?"
  },
  {
    "id": "father_status",
    "cat": "Decision & Consent",
    "q": "What is your FATHER'S (or primary male guardian's) circumcision state, to the best of your knowledge?",
    "opts": [
      "Circumcised",
      "Intact",
      "Don't know",
      "N/A"
    ],
    "colors": [
      "#d94f4f",
      "#5b93c7",
      "#a0a0a0",
      "#a0a0a0"
    ],
    "data": {
      "circumcised": [
        67.1,
        24.2,
        7.7,
        1.0
      ],
      "restoring": [
        75.2,
        15.6,
        7.3,
        1.8
      ]
    },
    "note": "Asked of Circumcised and Restoring respondents.",
    "pathways": [
      "circumcised",
      "restoring"
    ]
  },
  {
    "id": "restoration_considered",
    "cat": "Decision & Consent",
    "q": "Have you ever considered or researched options like foreskin RESTORATION or REGENERATION?",
    "opts": [
      "Actively researching",
      "Seriously considered",
      "Briefly considered",
      "Never considered",
      "No",
      "Unsure/never heard"
    ],
    "colors": [
      "#5b93c7",
      "#8bb8d9",
      "#e8c868",
      "#e8a44a",
      "#d94f4f",
      "#a0a0a0"
    ],
    "data": {
      "circumcised": [
        27.5,
        24.0,
        23.0,
        15.7,
        7.8,
        2.0
      ]
    },
    "note": "Asked of Circumcised Pathway respondents only.",
    "pathways": [
      "circumcised"
    ],
    "sub": "Restoration uses gradual skin-stretching methods to regrow foreskin coverage over the glans. Regeneration refers to biomedical approaches to grow new foreskin tissue, like Foregen's research."
  },
  {
    "id": "aesthetics",
    "cat": "Beliefs & Perceptions",
    "q": "Purely in terms of AESTHETICS (visual appearance), which look do you personally find more appealing?",
    "opts": [
      "Strongly prefer intact",
      "Slightly prefer intact",
      "No preference",
      "Slightly prefer circ",
      "Strongly prefer circ"
    ],
    "colors": [
      "#5b93c7",
      "#8bb8d9",
      "#e8c868",
      "#e8a44a",
      "#d94f4f"
    ],
    "data": {
      "intact": [
        65.2,
        14.5,
        8.0,
        6.5,
        5.8
      ],
      "circumcised": [
        52.0,
        10.8,
        9.3,
        7.8,
        20.1
      ],
      "restoring": [
        90.7,
        2.8,
        3.7,
        1.9,
        0.9
      ],
      "observer": [
        48.5,
        12.1,
        18.2,
        15.2,
        6.1
      ]
    }
  },
  {
    "id": "med_superior",
    "cat": "Beliefs & Perceptions",
    "q": "Putting aside your personal satisfaction or feelings, which state do you generally believe to be MEDICALLY HEALTHIER or more HYGIENIC overall?",
    "opts": [
      "Intact slightly",
      "Intact significantly",
      "No difference",
      "Circ slightly",
      "Circ significantly",
      "Unsure"
    ],
    "colors": [
      "#8bb8d9",
      "#5b93c7",
      "#e8c868",
      "#e8a44a",
      "#d94f4f",
      "#a0a0a0"
    ],
    "data": {
      "intact": [
        34.3,
        32.8,
        19.7,
        7.3,
        2.9,
        2.9
      ],
      "circumcised": [
        23.6,
        31.0,
        16.3,
        13.3,
        12.3,
        3.4
      ],
      "restoring": [
        28.7,
        48.1,
        13.9,
        5.6,
        2.8,
        0.9
      ],
      "observer": [
        15.2,
        48.5,
        24.2,
        6.1,
        3.0,
        3.0
      ]
    },
    "sub": "This question is about your intellectual belief regarding health outcomes, based on everything you've heard or learned in your life."
  }
],
  "mirrorPairs": [
    {
      "id": "resentment_mirror",
      "title": "Resentment vs Regret",
      "note": "We use 'resentment' for the Circumcised Pathway because the procedure was performed without their agency. We use 'regret' for the Intact Pathway because that is the word that could meaningfully apply to a state they grew into. This distinction was shaped by community feedback.",
      "left": {
        "pathway": "circumcised",
        "q": "Have you experienced resentment, loss, anger, or grief about your circumcision?",
        "opts": [
          "Strong & frequent",
          "No, never",
          "Sometimes",
          "Rarely"
        ],
        "data": [
          54.6,
          21.0,
          16.1,
          8.3
        ]
      },
      "right": {
        "pathway": "intact",
        "q": "Have you ever wished you were circumcised, or felt regret about being intact?",
        "opts": [
          "No, never",
          "Rarely",
          "Sometimes",
          "Strong & frequent"
        ],
        "data": [
          61.9,
          18.0,
          11.5,
          8.6
        ]
      },
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#5b93c7"
      ]
    },
    {
      "id": "restoring_resentment",
      "title": "Restoration Pathway: Resentment",
      "sub": "Every restoring respondent reports negative feelings — 0% 'No, never' (n=103)",
      "left": {
        "pathway": "restoring",
        "q": "Have you experienced resentment, loss, anger, or grief about your circumcision?",
        "opts": [
          "Strong & frequent",
          "Sometimes",
          "Rarely"
        ],
        "data": [
          79.6,
          15.5,
          4.9
        ]
      },
      "right": {
        "pathway": "circumcised",
        "q": "Have you experienced resentment, loss, anger, or grief about your circumcision?",
        "opts": [
          "Strong & frequent",
          "No, never",
          "Sometimes",
          "Rarely"
        ],
        "data": [
          54.6,
          21.0,
          16.1,
          8.3
        ]
      },
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#5b93c7"
      ]
    },
    {
      "id": "curiosity_mirror",
      "title": "Curiosity About the Other Anatomy",
      "left": {
        "pathway": "circumcised",
        "q": "Have you wondered what sex would be like with an intact penis?",
        "opts": [
          "Often wondered",
          "Before being circ",
          "Occasionally",
          "Happy as is",
          "Circ preferable",
          "Never thought"
        ],
        "data": [
          67.8,
          15.1,
          10.7,
          3.9,
          2.0,
          0.5
        ]
      },
      "right": {
        "pathway": "intact",
        "q": "Have you wondered what sex would be like if you were circumcised?",
        "opts": [
          "Occasionally",
          "Often wondered",
          "Intact preferable",
          "Happy as is",
          "Never thought"
        ],
        "data": [
          41.7,
          27.3,
          20.1,
          7.9,
          2.9
        ]
      },
      "colors": [
        "#d94f4f",
        "#e8a44a",
        "#e8c868",
        "#8bb8d9",
        "#5b93c7",
        "#a0a0a0"
      ]
    }
  ],
  "curatedSections": [
    {
      "id": "pleasure_gap",
      "title": "The Pleasure Gap",
      "desc": "Self-reported sexual experience ratings across pathways",
      "question_ids": [
        "mobile",
        "light",
        "variety",
        "ease",
        "intensity",
        "duration_r",
        "confidence"
      ]
    },
    {
      "id": "lubrication",
      "title": "The Lubrication Deficit",
      "desc": "Functional self-sufficiency by pathway",
      "question_ids": [
        "lube",
        "duration"
      ]
    },
    {
      "id": "resentment",
      "title": "Resentment & Regret",
      "desc": "The asymmetric weight of being chosen for vs born into",
      "question_ids": [
        "resentment_mirror",
        "restoring_resentment",
        "pride"
      ]
    },
    {
      "id": "generational",
      "title": "The Generational Break",
      "desc": "Future-son intentions across every pathway",
      "question_ids": [
        "sons",
        "father_status"
      ]
    },
    {
      "id": "autonomy_consensus",
      "title": "Bodily Autonomy Consensus",
      "desc": "Where all pathways converge",
      "question_ids": [
        "autonomy"
      ]
    },
    {
      "id": "systemic",
      "title": "The Systemic Failure",
      "desc": "How decisions were actually made",
      "question_ids": [
        "handled",
        "norm"
      ]
    },
    {
      "id": "perception",
      "title": "Cross-Pathway Perception",
      "desc": "How each pathway sees the other and the aesthetic landscape",
      "question_ids": [
        "curiosity_mirror",
        "aesthetics",
        "med_superior"
      ]
    }
  ]
};

export const META             = _data.meta;
export const PATHWAY          = _data.pathway;
export const ALL_QUESTIONS    = _data.questions;
export const MIRROR_PAIRS     = _data.mirrorPairs;
export const CURATED_SECTIONS = _data.curatedSections;

// ── Curated quotes — reviewed by Tone, never auto-generated ──
export const QUOTE_GALLERIES = {
  resentment_mirror: {
    circumcised: [
      { text: "Pain. Loss of pleasure. Loss of confidence. Loss of trust. Self hatred. Depression.", context: "On drawbacks" },
      { text: "I, at 57 years old, have never had a normal intimate relationship... the mutilation is always there.", context: "On lifelong impact" },
      { text: "Negative impact to how I experience pleasure. Not being able to experience the build-up to orgasm from 0–10.", context: "On sensory experience" },
    ],
    intact: [
      { text: "In childhood and through college I was self conscious because all of my friends were cut and I only knew one other kid who was uncut.", context: "On regret triggers" },
      { text: "Only as a teen/young adult due to stigma arising from movies, pop culture, etc.", context: "On the source of regret" },
    ],
  },
  pride: {
    circumcised: [
      { text: "Sexual problems, skin tearing, not enough skin to accommodate it, low self esteem, avoiding intimacy.", context: "On daily reality" },
    ],
    intact: [
      { text: "Felt awkward in high school but never a concern.", context: "On growing up intact" },
    ],
  },
};
