// ═══════════════════════════════════════════════════════════════
// CircumSurvey — Auto-generated demographic cross-tabs
// Generated: 2026-04-18 15:44 UTC
// DO NOT EDIT MANUALLY — regenerated by scripts/demographics.py
// ═══════════════════════════════════════════════════════════════

const _demographics = {
  "generatedAt": "2026-04-18T15:44:48.060386+00:00",
  "totalRespondents": 459,
  "minCellSize": 5,
  "baseRate": {
    "total": 459,
    "intact": 140,
    "circumcised": 319,
    "observer": 0,
    "pct_intact": 30.5,
    "pct_circumcised": 69.5,
    "pct_observer": 0.0
  },
  "dimensions": [
    {
      "id": "family_politics",
      "label": "Family's political lean during upbringing",
      "short": "Politics",
      "categories": [
        {
          "category": "Very liberal / far left",
          "total": 15,
          "intact": 3,
          "circumcised": 8,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 20.0,
          "pct_circumcised": 80.0,
          "pct_observer": 0.0
        },
        {
          "category": "Liberal / left-leaning",
          "total": 99,
          "intact": 38,
          "circumcised": 39,
          "restoring": 22,
          "observer": 0,
          "pct_intact": 38.4,
          "pct_circumcised": 61.6,
          "pct_observer": 0.0
        },
        {
          "category": "Libertarian / independent / apolitical",
          "total": 47,
          "intact": 13,
          "circumcised": 25,
          "restoring": 9,
          "observer": 0,
          "pct_intact": 27.7,
          "pct_circumcised": 72.3,
          "pct_observer": 0.0
        },
        {
          "category": "Moderate / centrist",
          "total": 104,
          "intact": 34,
          "circumcised": 50,
          "restoring": 20,
          "observer": 0,
          "pct_intact": 32.7,
          "pct_circumcised": 67.3,
          "pct_observer": 0.0
        },
        {
          "category": "Conservative / right-leaning",
          "total": 106,
          "intact": 31,
          "circumcised": 41,
          "restoring": 34,
          "observer": 0,
          "pct_intact": 29.2,
          "pct_circumcised": 70.8,
          "pct_observer": 0.0
        },
        {
          "category": "Very conservative / far right",
          "total": 51,
          "intact": 7,
          "circumcised": 30,
          "restoring": 14,
          "observer": 0,
          "pct_intact": 13.7,
          "pct_circumcised": 86.3,
          "pct_observer": 0.0
        },
        {
          "category": "Other / prefer not to say",
          "total": 26,
          "intact": 10,
          "circumcised": 12,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 38.5,
          "pct_circumcised": 61.5,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown / prefer not to say",
          "total": 11,
          "intact": 4,
          "circumcised": 5,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 36.4,
          "pct_circumcised": 63.6,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "mother_edu",
      "label": "Mother's education level",
      "short": "Mother's education",
      "categories": [
        {
          "category": "High school or GED",
          "total": 160,
          "intact": 48,
          "circumcised": 80,
          "restoring": 32,
          "observer": 0,
          "pct_intact": 30.0,
          "pct_circumcised": 70.0,
          "pct_observer": 0.0
        },
        {
          "category": "Associate's / Some college / Trade",
          "total": 79,
          "intact": 20,
          "circumcised": 30,
          "restoring": 29,
          "observer": 0,
          "pct_intact": 25.3,
          "pct_circumcised": 74.7,
          "pct_observer": 0.0
        },
        {
          "category": "Bachelor's degree",
          "total": 112,
          "intact": 33,
          "circumcised": 53,
          "restoring": 26,
          "observer": 0,
          "pct_intact": 29.5,
          "pct_circumcised": 70.5,
          "pct_observer": 0.0
        },
        {
          "category": "Master's degree",
          "total": 65,
          "intact": 22,
          "circumcised": 28,
          "restoring": 15,
          "observer": 0,
          "pct_intact": 33.8,
          "pct_circumcised": 66.2,
          "pct_observer": 0.0
        },
        {
          "category": "Doctorate / Professional",
          "total": 18,
          "intact": 8,
          "circumcised": 6,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 44.4,
          "pct_circumcised": 55.6,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown / prefer not to say",
          "total": 8,
          "intact": 2,
          "circumcised": 4,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 25.0,
          "pct_circumcised": 75.0,
          "pct_observer": 0.0
        },
        {
          "category": "I'm not sure / Prefer not to say",
          "total": 15,
          "intact": 6,
          "circumcised": 9,
          "restoring": 0,
          "observer": 0,
          "pct_intact": 40.0,
          "pct_circumcised": 60.0,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "father_edu",
      "label": "Father's education level",
      "short": "Father's education",
      "categories": [
        {
          "category": "High school or GED",
          "total": 133,
          "intact": 45,
          "circumcised": 62,
          "restoring": 26,
          "observer": 0,
          "pct_intact": 33.8,
          "pct_circumcised": 66.2,
          "pct_observer": 0.0
        },
        {
          "category": "Associate's / Some college / Trade",
          "total": 82,
          "intact": 22,
          "circumcised": 32,
          "restoring": 28,
          "observer": 0,
          "pct_intact": 26.8,
          "pct_circumcised": 73.2,
          "pct_observer": 0.0
        },
        {
          "category": "Bachelor's degree",
          "total": 108,
          "intact": 29,
          "circumcised": 54,
          "restoring": 25,
          "observer": 0,
          "pct_intact": 26.9,
          "pct_circumcised": 73.1,
          "pct_observer": 0.0
        },
        {
          "category": "Master's degree",
          "total": 72,
          "intact": 29,
          "circumcised": 28,
          "restoring": 15,
          "observer": 0,
          "pct_intact": 40.3,
          "pct_circumcised": 59.7,
          "pct_observer": 0.0
        },
        {
          "category": "Doctorate / Professional",
          "total": 29,
          "intact": 6,
          "circumcised": 13,
          "restoring": 10,
          "observer": 0,
          "pct_intact": 20.7,
          "pct_circumcised": 79.3,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown / prefer not to say",
          "total": 12,
          "intact": 2,
          "circumcised": 7,
          "restoring": 3,
          "observer": 0,
          "pct_intact": 16.7,
          "pct_circumcised": 83.3,
          "pct_observer": 0.0
        },
        {
          "category": "I'm not sure / Prefer not to say",
          "total": 18,
          "intact": 5,
          "circumcised": 12,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 27.8,
          "pct_circumcised": 72.2,
          "pct_observer": 0.0
        },
        {
          "category": "Not applicable",
          "total": 5,
          "intact": 2,
          "circumcised": 2,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 40.0,
          "pct_circumcised": 60.0,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "family_ses",
      "label": "Family's socioeconomic status (childhood)",
      "short": "Family SES",
      "categories": [
        {
          "category": "Poor / struggling",
          "total": 28,
          "intact": 7,
          "circumcised": 12,
          "restoring": 9,
          "observer": 0,
          "pct_intact": 25.0,
          "pct_circumcised": 75.0,
          "pct_observer": 0.0
        },
        {
          "category": "Working / lower-middle",
          "total": 122,
          "intact": 38,
          "circumcised": 57,
          "restoring": 27,
          "observer": 0,
          "pct_intact": 31.1,
          "pct_circumcised": 68.9,
          "pct_observer": 0.0
        },
        {
          "category": "Middle",
          "total": 190,
          "intact": 58,
          "circumcised": 90,
          "restoring": 42,
          "observer": 0,
          "pct_intact": 30.5,
          "pct_circumcised": 69.5,
          "pct_observer": 0.0
        },
        {
          "category": "Upper-middle",
          "total": 97,
          "intact": 29,
          "circumcised": 41,
          "restoring": 27,
          "observer": 0,
          "pct_intact": 29.9,
          "pct_circumcised": 70.1,
          "pct_observer": 0.0
        },
        {
          "category": "Upper / wealthy",
          "total": 11,
          "intact": 4,
          "circumcised": 5,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 36.4,
          "pct_circumcised": 63.6,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown",
          "total": 8,
          "intact": 1,
          "circumcised": 5,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 12.5,
          "pct_circumcised": 87.5,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "religion_significant",
      "label": "Religion significant during upbringing",
      "short": "Religious upbringing",
      "categories": [
        {
          "category": "Yes \u2014 significant",
          "total": 363,
          "intact": 105,
          "circumcised": 170,
          "restoring": 88,
          "observer": 0,
          "pct_intact": 28.9,
          "pct_circumcised": 71.1,
          "pct_observer": 0.0
        },
        {
          "category": "No / secular",
          "total": 64,
          "intact": 25,
          "circumcised": 24,
          "restoring": 15,
          "observer": 0,
          "pct_intact": 39.1,
          "pct_circumcised": 60.9,
          "pct_observer": 0.0
        },
        {
          "category": "Other",
          "total": 24,
          "intact": 8,
          "circumcised": 11,
          "restoring": 5,
          "observer": 0,
          "pct_intact": 33.3,
          "pct_circumcised": 66.7,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown",
          "total": 8,
          "intact": 2,
          "circumcised": 5,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 25.0,
          "pct_circumcised": 75.0,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "primary_tradition",
      "label": "Primary religious tradition during upbringing",
      "short": "Religious tradition",
      "categories": [
        {
          "category": "Jewish",
          "total": 10,
          "intact": 3,
          "circumcised": 3,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 30.0,
          "pct_circumcised": 70.0,
          "pct_observer": 0.0
        },
        {
          "category": "Muslim / Islamic",
          "total": 9,
          "intact": 1,
          "circumcised": 7,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 11.1,
          "pct_circumcised": 88.9,
          "pct_observer": 0.0
        },
        {
          "category": "Other Christian",
          "total": 208,
          "intact": 51,
          "circumcised": 97,
          "restoring": 60,
          "observer": 0,
          "pct_intact": 24.5,
          "pct_circumcised": 75.5,
          "pct_observer": 0.0
        },
        {
          "category": "None / secular",
          "total": 226,
          "intact": 80,
          "circumcised": 103,
          "restoring": 43,
          "observer": 0,
          "pct_intact": 35.4,
          "pct_circumcised": 64.6,
          "pct_observer": 0.0
        },
        {
          "category": "Other / smaller groups (combined)",
          "total": 6,
          "intact": 5,
          "circumcised": 0,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 83.3,
          "pct_circumcised": 16.7,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "generation",
      "label": "Generation",
      "short": "Generation",
      "categories": [
        {
          "category": "Boomer (1946-1964)",
          "total": 45,
          "intact": 8,
          "circumcised": 27,
          "restoring": 10,
          "observer": 0,
          "pct_intact": 17.8,
          "pct_circumcised": 82.2,
          "pct_observer": 0.0
        },
        {
          "category": "Gen X (1965-1980)",
          "total": 64,
          "intact": 20,
          "circumcised": 31,
          "restoring": 13,
          "observer": 0,
          "pct_intact": 31.2,
          "pct_circumcised": 68.8,
          "pct_observer": 0.0
        },
        {
          "category": "Millennial (1981-1996)",
          "total": 175,
          "intact": 58,
          "circumcised": 70,
          "restoring": 47,
          "observer": 0,
          "pct_intact": 33.1,
          "pct_circumcised": 66.9,
          "pct_observer": 0.0
        },
        {
          "category": "Gen Z (1997-2012)",
          "total": 130,
          "intact": 35,
          "circumcised": 68,
          "restoring": 27,
          "observer": 0,
          "pct_intact": 26.9,
          "pct_circumcised": 73.1,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown",
          "total": 7,
          "intact": 2,
          "circumcised": 3,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 28.6,
          "pct_circumcised": 71.4,
          "pct_observer": 0.0
        },
        {
          "category": "Xennial/Oregon Trail (born app",
          "total": 24,
          "intact": 14,
          "circumcised": 6,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 58.3,
          "pct_circumcised": 41.7,
          "pct_observer": 0.0
        },
        {
          "category": "Not sure / Prefer not to say",
          "total": 10,
          "intact": 3,
          "circumcised": 3,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 30.0,
          "pct_circumcised": 70.0,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "age",
      "label": "Current age",
      "short": "Age",
      "categories": [
        {
          "category": "18-24",
          "total": 100,
          "intact": 26,
          "circumcised": 53,
          "restoring": 21,
          "observer": 0,
          "pct_intact": 26.0,
          "pct_circumcised": 74.0,
          "pct_observer": 0.0
        },
        {
          "category": "25-34",
          "total": 135,
          "intact": 37,
          "circumcised": 57,
          "restoring": 41,
          "observer": 0,
          "pct_intact": 27.4,
          "pct_circumcised": 72.6,
          "pct_observer": 0.0
        },
        {
          "category": "35-44",
          "total": 95,
          "intact": 41,
          "circumcised": 36,
          "restoring": 18,
          "observer": 0,
          "pct_intact": 43.2,
          "pct_circumcised": 56.8,
          "pct_observer": 0.0
        },
        {
          "category": "45-54",
          "total": 53,
          "intact": 15,
          "circumcised": 26,
          "restoring": 12,
          "observer": 0,
          "pct_intact": 28.3,
          "pct_circumcised": 71.7,
          "pct_observer": 0.0
        },
        {
          "category": "55-64",
          "total": 36,
          "intact": 13,
          "circumcised": 15,
          "restoring": 8,
          "observer": 0,
          "pct_intact": 36.1,
          "pct_circumcised": 63.9,
          "pct_observer": 0.0
        },
        {
          "category": "65+",
          "total": 33,
          "intact": 6,
          "circumcised": 21,
          "restoring": 6,
          "observer": 0,
          "pct_intact": 18.2,
          "pct_circumcised": 81.8,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown",
          "total": 7,
          "intact": 2,
          "circumcised": 2,
          "restoring": 3,
          "observer": 0,
          "pct_intact": 28.6,
          "pct_circumcised": 71.4,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "resp_edu",
      "label": "Respondent's education level",
      "short": "Your education",
      "categories": [
        {
          "category": "High school or GED",
          "total": 80,
          "intact": 28,
          "circumcised": 35,
          "restoring": 17,
          "observer": 0,
          "pct_intact": 35.0,
          "pct_circumcised": 65.0,
          "pct_observer": 0.0
        },
        {
          "category": "Associate's / Some college / Trade",
          "total": 108,
          "intact": 34,
          "circumcised": 45,
          "restoring": 29,
          "observer": 0,
          "pct_intact": 31.5,
          "pct_circumcised": 68.5,
          "pct_observer": 0.0
        },
        {
          "category": "Bachelor's degree",
          "total": 147,
          "intact": 37,
          "circumcised": 78,
          "restoring": 32,
          "observer": 0,
          "pct_intact": 25.2,
          "pct_circumcised": 74.8,
          "pct_observer": 0.0
        },
        {
          "category": "Master's degree",
          "total": 65,
          "intact": 18,
          "circumcised": 31,
          "restoring": 16,
          "observer": 0,
          "pct_intact": 27.7,
          "pct_circumcised": 72.3,
          "pct_observer": 0.0
        },
        {
          "category": "Doctorate / Professional",
          "total": 43,
          "intact": 19,
          "circumcised": 13,
          "restoring": 11,
          "observer": 0,
          "pct_intact": 44.2,
          "pct_circumcised": 55.8,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown / prefer not to say",
          "total": 15,
          "intact": 4,
          "circumcised": 8,
          "restoring": 3,
          "observer": 0,
          "pct_intact": 26.7,
          "pct_circumcised": 73.3,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "country_birth",
      "label": "Country of birth",
      "short": "Country",
      "categories": [
        {
          "category": "USA",
          "total": 286,
          "intact": 68,
          "circumcised": 131,
          "restoring": 87,
          "observer": 0,
          "pct_intact": 23.8,
          "pct_circumcised": 76.2,
          "pct_observer": 0.0
        },
        {
          "category": "Canada",
          "total": 40,
          "intact": 19,
          "circumcised": 16,
          "restoring": 5,
          "observer": 0,
          "pct_intact": 47.5,
          "pct_circumcised": 52.5,
          "pct_observer": 0.0
        },
        {
          "category": "United Kingdom",
          "total": 29,
          "intact": 13,
          "circumcised": 15,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 44.8,
          "pct_circumcised": 55.2,
          "pct_observer": 0.0
        },
        {
          "category": "Australia",
          "total": 17,
          "intact": 6,
          "circumcised": 7,
          "restoring": 4,
          "observer": 0,
          "pct_intact": 35.3,
          "pct_circumcised": 64.7,
          "pct_observer": 0.0
        },
        {
          "category": "Germany",
          "total": 15,
          "intact": 1,
          "circumcised": 12,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 6.7,
          "pct_circumcised": 93.3,
          "pct_observer": 0.0
        },
        {
          "category": "South Africa",
          "total": 5,
          "intact": 1,
          "circumcised": 2,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 20.0,
          "pct_circumcised": 80.0,
          "pct_observer": 0.0
        },
        {
          "category": "Other / smaller groups (combined)",
          "total": 67,
          "intact": 32,
          "circumcised": 27,
          "restoring": 8,
          "observer": 0,
          "pct_intact": 47.8,
          "pct_circumcised": 52.2,
          "pct_observer": 0.0
        }
      ]
    },
    {
      "id": "race",
      "label": "Race / ethnicity",
      "short": "Race / ethnicity",
      "categories": [
        {
          "category": "White / European",
          "total": 396,
          "intact": 119,
          "circumcised": 181,
          "restoring": 96,
          "observer": 0,
          "pct_intact": 30.1,
          "pct_circumcised": 69.9,
          "pct_observer": 0.0
        },
        {
          "category": "Black / African heritage",
          "total": 25,
          "intact": 1,
          "circumcised": 16,
          "restoring": 8,
          "observer": 0,
          "pct_intact": 4.0,
          "pct_circumcised": 96.0,
          "pct_observer": 0.0
        },
        {
          "category": "Asian",
          "total": 31,
          "intact": 11,
          "circumcised": 15,
          "restoring": 5,
          "observer": 0,
          "pct_intact": 35.5,
          "pct_circumcised": 64.5,
          "pct_observer": 0.0
        },
        {
          "category": "Hispanic / Latino",
          "total": 32,
          "intact": 14,
          "circumcised": 9,
          "restoring": 9,
          "observer": 0,
          "pct_intact": 43.8,
          "pct_circumcised": 56.2,
          "pct_observer": 0.0
        },
        {
          "category": "Native / Indigenous",
          "total": 13,
          "intact": 2,
          "circumcised": 6,
          "restoring": 5,
          "observer": 0,
          "pct_intact": 15.4,
          "pct_circumcised": 84.6,
          "pct_observer": 0.0
        },
        {
          "category": "Mixed / multiple",
          "total": 25,
          "intact": 3,
          "circumcised": 13,
          "restoring": 9,
          "observer": 0,
          "pct_intact": 12.0,
          "pct_circumcised": 88.0,
          "pct_observer": 0.0
        },
        {
          "category": "Unknown",
          "total": 5,
          "intact": 1,
          "circumcised": 2,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 20.0,
          "pct_circumcised": 80.0,
          "pct_observer": 0.0
        },
        {
          "category": "Prefer not to say",
          "total": 5,
          "intact": 0,
          "circumcised": 4,
          "restoring": 1,
          "observer": 0,
          "pct_intact": 0.0,
          "pct_circumcised": 100.0,
          "pct_observer": 0.0
        },
        {
          "category": "Other / smaller groups (combined)",
          "total": 5,
          "intact": 1,
          "circumcised": 2,
          "restoring": 2,
          "observer": 0,
          "pct_intact": 20.0,
          "pct_circumcised": 80.0,
          "pct_observer": 0.0
        }
      ],
      "note": "Multi-select: respondents identifying with multiple categories count in each."
    }
  ],
  "outlierFindings": [
    {
      "dimension_id": "country_birth",
      "dimension_label": "Country",
      "most_intact_category": "Canada",
      "most_intact_pct": 47.5,
      "most_intact_n": 40,
      "least_intact_category": "Germany",
      "least_intact_pct": 6.7,
      "least_intact_n": 15,
      "spread": 40.8
    },
    {
      "dimension_id": "generation",
      "dimension_label": "Generation",
      "most_intact_category": "Xennial/Oregon Trail (born app",
      "most_intact_pct": 58.3,
      "most_intact_n": 24,
      "least_intact_category": "Boomer (1946-1964)",
      "least_intact_pct": 17.8,
      "least_intact_n": 45,
      "spread": 40.5
    },
    {
      "dimension_id": "race",
      "dimension_label": "Race / ethnicity",
      "most_intact_category": "Hispanic / Latino",
      "most_intact_pct": 43.8,
      "most_intact_n": 32,
      "least_intact_category": "Black / African heritage",
      "least_intact_pct": 4.0,
      "least_intact_n": 25,
      "spread": 39.8
    },
    {
      "dimension_id": "age",
      "dimension_label": "Age",
      "most_intact_category": "35-44",
      "most_intact_pct": 43.2,
      "most_intact_n": 95,
      "least_intact_category": "65+",
      "least_intact_pct": 18.2,
      "least_intact_n": 33,
      "spread": 25.0
    },
    {
      "dimension_id": "family_politics",
      "dimension_label": "Politics",
      "most_intact_category": "Other / prefer not to say",
      "most_intact_pct": 38.5,
      "most_intact_n": 26,
      "least_intact_category": "Very conservative / far right",
      "least_intact_pct": 13.7,
      "least_intact_n": 51,
      "spread": 24.8
    },
    {
      "dimension_id": "father_edu",
      "dimension_label": "Father's education",
      "most_intact_category": "Master's degree",
      "most_intact_pct": 40.3,
      "most_intact_n": 72,
      "least_intact_category": "Doctorate / Professional",
      "least_intact_pct": 20.7,
      "least_intact_n": 29,
      "spread": 19.6
    },
    {
      "dimension_id": "mother_edu",
      "dimension_label": "Mother's education",
      "most_intact_category": "Doctorate / Professional",
      "most_intact_pct": 44.4,
      "most_intact_n": 18,
      "least_intact_category": "Associate's / Some college / Trade",
      "least_intact_pct": 25.3,
      "least_intact_n": 79,
      "spread": 19.1
    },
    {
      "dimension_id": "resp_edu",
      "dimension_label": "Your education",
      "most_intact_category": "Doctorate / Professional",
      "most_intact_pct": 44.2,
      "most_intact_n": 43,
      "least_intact_category": "Bachelor's degree",
      "least_intact_pct": 25.2,
      "least_intact_n": 147,
      "spread": 19.0
    },
    {
      "dimension_id": "family_ses",
      "dimension_label": "Family SES",
      "most_intact_category": "Upper / wealthy",
      "most_intact_pct": 36.4,
      "most_intact_n": 11,
      "least_intact_category": "Poor / struggling",
      "least_intact_pct": 25.0,
      "least_intact_n": 28,
      "spread": 11.4
    },
    {
      "dimension_id": "religion_significant",
      "dimension_label": "Religious upbringing",
      "most_intact_category": "No / secular",
      "most_intact_pct": 39.1,
      "most_intact_n": 64,
      "least_intact_category": "Yes \u2014 significant",
      "least_intact_pct": 28.9,
      "least_intact_n": 363,
      "spread": 10.2
    },
    {
      "dimension_id": "primary_tradition",
      "dimension_label": "Religious tradition",
      "most_intact_category": "Jewish",
      "most_intact_pct": 30.0,
      "most_intact_n": 10,
      "least_intact_category": "Other Christian",
      "least_intact_pct": 24.5,
      "least_intact_n": 208,
      "spread": 5.5
    }
  ]
};

export const DEMOGRAPHIC_DIMENSIONS = _demographics.dimensions;
export const DEMOGRAPHIC_BASE_RATE   = _demographics.baseRate;
export const DEMOGRAPHIC_OUTLIERS    = _demographics.outlierFindings;
export const DEMOGRAPHIC_META        = {
  generatedAt: _demographics.generatedAt,
  totalRespondents: _demographics.totalRespondents,
  minCellSize: _demographics.minCellSize,
};
